forumAPI/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from tastypie.api import Api

from forumSite import urls as site_urls
from forumAPI.api import TopicResource, CommentResource, UserResource, AdminUserResource, CreateUserResource
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

v1_api = Api(api_name='v1')
v1_api.register(TopicResource())
v1_api.register(CommentResource())
v1_api.register(UserResource())
v1_api.register(AdminUserResource())
v1_api.register(CreateUserResource())


urlpatterns = patterns('',
    (r'^accounts/profile/$', 'forumSite.views.index'),
    (r'^accounts/', include('registration.urls')),
    (r'^api/', include(v1_api.urls)),
    ('^admin/', include(admin.site.urls)),
    (r'^static/', 'django.views.static.serve', {'document_root' : 'forumAPI/static', 'show_indexes' : True}),
    ('', include(site_urls)),
)

urlpatterns = staticfiles_urlpatterns() + urlpatterns

forumSite/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
#    (r'^topic/<?P>', views.topic()),
    ('^register/?$', 'forumSite.views.signup'),
    ('^topics/$', 'forumSite.views.topics'),
    ('^submit/topic/?$', 'forumSite.views.newtopic'),
    ('topic/(?P<id>[a-zA-Z0-9]{1,})/$', 'forumSite.views.topic'),
    ('comment/(?P<id>[a-zA-Z0-9]{1,})/delete/$', 'forumSite.views.delete_comment'),
    ('comment/(?P<id>[a-zA-Z0-9]{1,})/hide/$', 'forumSite.views.hide_comment'),
    ('comment/(?P<id>[a-zA-Z0-9]{1,})/$', 'forumSite.views.edit_comment'),
    ('^topic/?$', 'forumSite.views.topic'),
#     ('^addcomment', 'forumSite.views.addcomment'),
    ('^$', 'forumSite.views.index')
)

forumSite/forms.py
import requests
import logging

from django import forms
from django.utils.translation import ugettext as _
from django.contrib.auth.models import User
from django.db import models

import api_client

logger = logging.getLogger(__name__)

def _drop_empty_id(my_vals):
    if 'id' in my_vals and not my_vals['id']:
        del my_vals['id']
    return my_vals

class ApiForm(forms.Form):
    id = forms.CharField(widget=forms.HiddenInput, required=False)

    def save(self, request=None):
        try:
            res = api_client.save(self, request=request)
            res.raise_for_status()
        except (requests.exceptions.HTTPError) as err:
            logger.error(err)
            raise err
#            return False
        return True

class UserForm(ApiForm):
    class Meta:
        api_path = "user/"
    

class SignupForm(UserForm):
    
    class Meta(UserForm.Meta):
        api_path = "register/"
        fields = ('email', 'username')
    def to_dict(self, request=None):
        my_vals = {
                    'email': self.cleaned_data.get('email', ''),
                    'username': self.cleaned_data.get('username', ''),
                    'password': self.cleaned_data.get('password', None),
                    'id': self.cleaned_data.get('id', None)
                  }
        if not my_vals['password']:
            del my_vals['password']
        if not my_vals['id']:
            del my_vals['id']
        return my_vals

    email = forms.EmailField(required = True)
    username = forms.CharField(max_length=50)
    password1 = forms.CharField(widget=forms.PasswordInput(render_value=False),
                                label=_("Password"))
    password2 = forms.CharField(widget=forms.PasswordInput(render_value=False),
                                label=_("Password (again)"))

    def clean(self):
        """
        Verifiy that the values entered into the two password fields
        match.
        """
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError("The two password fields didn't match.")
            self.cleaned_data['password'] = self.cleaned_data['password1']
        return self.cleaned_data    

class TopicForm(ApiForm):
    class Meta:
        api_path = "topic/"
        fields = ('name', 'blurb')

    _logger = logging.getLogger(__name__)

    name = forms.CharField(max_length=50, required=True, label="Topic")
    blurb = forms.CharField(max_length=500, required=False, widget=forms.Textarea, label="Summary")
    id = forms.CharField(widget=forms.HiddenInput, required=False)

    def to_dict(self, request=None):
        my_vals = {
                    'name': self.cleaned_data.get('name', None),
                    'blurb': self.cleaned_data.get('blurb', None),
                    'id': self.cleaned_data.get('id', None)
                  }
        return _drop_empty_id(my_vals)
    
class CommentForm(ApiForm):
    class Meta:
        api_path = "comment/"
        fields = ('topic', 'in_reply_to', 'comment_body', 'id')
        exclude = ("is_hidden",)

    _logger = logging.getLogger(__name__)

    topic = forms.CharField(max_length=500, required=True, widget=forms.HiddenInput)
    comment_body = forms.CharField(required=True, widget=forms.Textarea, label="Comment")
    
    in_reply_to = forms.CharField(widget=forms.HiddenInput, required=False)

    def clean_topic(self):
        data = self.cleaned_data['topic']
        if data:
            return "{}/{}/{}/".format(api_client.API_PATH, 'topic', data)
        else:
            raise forms.ValidationError("No topic specified")
    
    def clean_in_reply_to(self):
        data = self.cleaned_data['in_reply_to']
        if not data:
            return None
        else:
            return data

    def to_dict(self, request=None):
        my_vals = {
                    'topic': self.cleaned_data.get('topic', None),
                    'in_reply_to': self.cleaned_data.get('in_reply_to', None),
                    'comment_body': self.cleaned_data.get('comment_body', None),
                    'author': request.user.username,
                    'id': self.cleaned_data.get('id', None)
                  }
        return _drop_empty_id(my_vals)

forumSite/views.py
import datetime
import logging

from django import forms
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render, get_object_or_404,\
    render_to_response
from django.utils.translation import ugettext as _
from django.template.context import RequestContext
from django.http import Http404
from django.forms.models import modelformset_factory
from django.forms.formsets import formset_factory
from django.contrib import messages

from forms import SignupForm, TopicForm, CommentForm
from forumSite import api_client
from django.http.response import HttpResponse

logger = logging.getLogger(__name__)

def signup(request):
    form = SignupForm()
    if request.POST:
        form = SignupForm(request.POST)
        if form.is_valid() and form.save():
            return render(request, "registration/registration_complete.html")
    return render(request, "registration/registration_form.html", {"form": form},
                  context_instance=RequestContext(request))

def topics(request):
    topic = TopicForm()
    topics = api_client.get(topic)
    return render(request, 'forum/topiclist.html', {'topics': topics['objects'], 'meta': topics['meta']})

def topic(request, id=None):
    form = TopicForm(initial={'id':id})
    comment_form = CommentForm(initial={"topic": id})
    if (request.POST):
        comment_form = CommentForm(request.POST)
        comment_form.user = request.user.username
        if comment_form.is_valid():
            if comment_form.save(request=request):
                message = "Comment submitted"
                return redirect('/topic/{}'.format(id))
            else:
                message = "Failed to save comment"
        else:
            pass
    try:
        topic = api_client.get(form)
        comments = api_client.get(form, sub_url="topic/{}/comments".format(id))
    except (Exception) as err:
        message = "Failed to retrieve topic and/or comments"
    
    new_comments = {}
    class node():
        def __init__(self, value):
            self.value = value
            self.children = []
    
        def add_child(self, obj):
            self.children.append(obj)
           
    nodes = dict((e["id"], node(e)) for e in comments['objects'])
    for e in comments['objects']:
        if e["in_reply_to"]:
            if not nodes.get(e["in_reply_to"], False):
                nodes[e["in_reply_to"]] = node({"is_hidden": True})
            nodes[e["in_reply_to"]].add_child(nodes[e["id"]])
            
    return render(request, 'forum/topic.html', {'topic': topic, 'comments': nodes, 'form': comment_form})
    
@login_required
def newtopic(request):
    user = request.user
    form = None
    if request.method == 'POST':
        form = TopicForm(request.POST)
        if form.is_valid() and form.save():
            return redirect('/topics/')
        elif form.is_valid():
            form.non_field_errors = "Failed to save"
        else:
            form.non_field_errors = 'form is not valid'
    else:
        form = TopicForm()
    return render(request, 'forum/form.html', {"form": form})

@login_required
def edit_comment(request, id):
    if request.POST:
        comment_form = CommentForm(request.POST, initial={'id': id})
        payload = {'comment_body': request.POST['comment_body']}
        if api_client.save(comment_form, method='PATCH', payload=payload):
            return redirect('/topic/' + request.POST.get('topic', "-empty-") + "/")
        else:
            message = "Failed ot save comment"
    skeleton = CommentForm(initial={'id': id})
    comment = api_client.get(skeleton)
    comment_form = CommentForm(initial={'comment_body':comment['comment_body'],
                                        'topic': comment['topic'].split("/")[-2]})
    return render(request, 'forum/form.html', {'form': comment_form, 'title': 'Edit Comment'})
    
@login_required
def delete_comment(request, id):
    if request.POST:
        comment_form = CommentForm(initial={'id': id})
        if api_client.delete(comment_form):
            return redirect('/topic/' + request.POST.get('topic', "-empty-") + "/")
        else:
            message = "Failed to delete comment"
            return redirect('/topic/' + request.POST.get('topic', "-empty-") + "/")


@login_required
def hide_comment(request, id):
    if request.POST:
        comment_form = CommentForm(initial={'id': id})
        payload = {'is_hidden': True}
        if api_client.save(comment_form, method='PATCH', payload=payload):
            return redirect('/topic/' + request.POST.get('topic', "-empty-") + "/")
        else:
            message = "Failed ot save comment"
        return redirect('/topic/' + request.POST.get('topic', "-empty-") + "/")

def index(request):
    return render_to_response('forum/index.html', { 'form': SignupForm()},
                              context_instance=RequestContext(request))

forumSite/templates/forum/comment.html
<div class="well well-sm col-sm-offset-{{comment.nesting_level}}">
    {% with comment_item.value as comment %}
    {%if comment.is_hidden %}
    <div class="hidden-comment">This comment has been hidden by a moderator</div>
    {%else%}
    <div class="row"><span class="col-lg-4"><span class="author">{{comment.author}}</span>&nbsp; {{ comment.created }}</span></div> 
    <div class="row">&nbsp;</div>
    <div class="row"><div class="col-lg-12">{{comment.comment_body}}</div></div>
    {% if user.is_authenticated %}
    <div class="row">
        <div class="col-lg-1"><a class="replylink btn btn-sm" href="#" rel="{{comment.id}}"><span class="glyphicon glyphicon-comment"></span> Reply</a></div>

        {% if comment.author == user.username %}
          <div class="col-lg-4"><a class="editlink btn btn-sm" href="/comment/{{comment.id}}/"><span class="glyphicon glyphicon-edit"></span> Edit Comment</a>
          &nbsp;<a class="deletelink btn btn-sm" rel="{{comment.id}}"><span class="glyphicon glyphicon-trash"></span> Delete Comment</a></div>
        {% endif %}
      {%if user.is_staff %}
            <div class="col-lg-2"><a class="hidelink btn btn-sm" href="#" rel="{{comment.id}}"><span class="glyphicon glyphicon-eye-close"></span> Hide this comment</a></div>
      {% endif %}
    </div>
    {% endif %}
    {%endif%}

    {%endwith%}
</div>

forumSite/templates/forum/form.html
{% extends "base.html" %}
{% load add_class %}
{% block title %}{{ title }}{% endblock %}

{% if errror %}
{% endif %}
{% block content %}
{% load i18n %}
  <form class="form-vertical " method="post" >{% csrf_token %}
    {% for hidden in form.hidden_fields %}
    {{ hidden }}
    {% endfor %}
    <fieldset>
      <div id="legend" class="">
        <legend class="">{{ title }}</legend>
      </div>
        {{ form.non_field_errors }}
        {% for field in form.visible_fields %}
    <div class="form-group row{%if field.errors %} has-error{% endif %}">
          <!-- Text input-->
          <label class="control-label col-lg-2" for="{{ field.name }}">{{ field.label_tag }}</label>
          <div class="controls col-lg-10">
            {{ field|add_class:"form-control" }} {{ field.errors }}
            {% if mobile %} <p class="help-block">{{ field.help_text }}</p> {% endif %}
          </div>
        </div>
    {% endfor %}

        <div class="control-group">

          <!-- Button -->
          <div class="controls">
            <button class="btn btn-primary">Submit</button>

          </div>
        </div>
        </fieldset>
  </form>
{%endblock%}

forumSite/templates/forum/index.html
{% extends "base.html" %}{% load i18n %}
{% block title %}Forums: Home{% endblock %}
{% block content %}
<header id="overview" class="jumbotron subhead logo">
  <h1>The Best Forums</h1>
  <p class="lead">Get your discussion on.</p>

</header>
      <div class="row-fluid">
          <div class="row">
          <div class="span8 hero-unit heroimage">
            <h2>Online Conversations easy!</h2>
            <p>This is the home page</p>
            </div>
            <div class="span4">
            </div>
        </div>
      </div>
{% endblock %}

forumSite/templates/forum/topic.html
{% extends "base.html" %}
{% load i18n %}
{% load add_class %}
{% block title %}{{ title }}{% endblock %}

{% if errror %}
{% endif %}
{% block content %}
{% autoescape on %}
<div class="row">
<h1>{{topic.name}}</h1>
<p>{{topic.blurb}}</p>
</div>
<div class="comments">
    <legend>Comments</legend>
    {%for key, comment_item in comments.items%}
    {%with comment_item.value as comment%}
    <div class="well well-sm col-sm-offset-{{comment.nesting_level}}">
        {%if comment.is_hidden %}
        <div class="hidden-comment">This comment has been hidden by a moderator</div>
        {%else%}
        <div class="row"><span class="col-lg-4"><span class="author">{{comment.author}}</span>&nbsp; {{ comment.created }}</span></div> 
        <div class="row">&nbsp;</div>
        <div class="row"><div class="col-lg-12">{{comment.comment_body}}</div></div>
        {% if user.is_authenticated %}
        <div class="row">
            <div class="col-lg-1"><a class="replylink btn btn-sm" href="#" rel="{{comment.id}}"><span class="glyphicon glyphicon-comment"></span> Reply</a></div>

            {% if comment.author == user.username %}
              <div class="col-lg-4"><a class="editlink btn btn-sm" href="/comment/{{comment.id}}/"><span class="glyphicon glyphicon-edit"></span> Edit Comment</a>
              &nbsp;<a class="deletelink btn btn-sm" rel="{{comment.id}}"><span class="glyphicon glyphicon-trash"></span> Delete Comment</a></div>
            {% endif %}
          {%if user.is_staff %}
                <div class="col-lg-2"><a class="hidelink btn btn-sm" href="#" rel="{{comment.id}}"><span class="glyphicon glyphicon-eye-close"></span> Hide this comment</a></div>
          {% endif %}
        </div>
        {% endif %}
        {%endif%}
        {%for node in comment_item.children%}
        {% with node as comment_item %}
        {% include 'forum/comment.html' %}
        {%endwith%}
        {%endfor%}     
    </div>
    {% endwith%}
    {% empty %}
    There are no comments yet. Be the first
    {% endfor %}
    
  {% if user.is_authenticated %}
  <form class="form-vertical " method="post" >{% csrf_token %}
    {% for hidden in form.hidden_fields %}
    {{ hidden }}
    {% endfor %}
    <fieldset>
        {{ form.non_field_errors }}
        {% for field in form.visible_fields %}
    <div class="form-group row{%if field.errors %} has-error{% endif %}">
          <label class="control-label col-lg-1" for="{{ field.name }}">{{ field.label_tag }}</label>
          <div class="controls col-lg-11">
            {{ field|add_class:"form-control" }} {{ field.errors }}
            {% if mobile %} <p class="help-block">{{ field.help_text }}</p> {% endif %}
          </div>
        </div>
    {% endfor %}
        <div class="control-group">

          <!-- Button -->
          <div class="controls">
            <button class="btn btn-primary">Submit</button>

          </div>
        </div>
    </fieldset>
  </form>
  {% else %}
  {% trans "You need to be logged in to post a comment" %}
  {% endif %}
</div>
<form id="hiddenform" method="post" action="">{%csrf_token%}
<input type="hidden" name="topic" value="{{topic.id}}" />
</form>
{% endautoescape %}
{%endblock%}
{% block javascript %}
<script type="text/javascript">
$(document).ready(function(){
    $('.replylink').click(function(){
        $('#id_in_reply_to').val($(this).attr('rel'));
        $("body").animate({
         scrollTop: $('#id_comment_body').offset().top
        }, 300);
        $('#id_comment_body').focus();
    });
    $('.deletelink').click(function(){
        if (!confirm("Are you sure you want to delete the comment?")){
            return false;
        }
        $('#hiddenform').prop('action', '/comment/' + $(this).prop('rel') + '/delete/');
        $('#hiddenform').submit();
    });
    $('.hidelink').click(function(){
        if (!confirm("Are you sure you want to hide the comment?")){
            return false;
        }
        $('#hiddenform').prop('action', '/comment/' + $(this).prop('rel') + '/hide/');
        $('#hiddenform').submit();
    });
});
</script>
{%endblock%}

forumSite/templates/forum/topiclist.html
{% extends "base.html" %}
{% load add_class %}
{% block title %}{{ title }}{% endblock %}

{% if errror %}
{% endif %}
{% block content %}
{% autoescape on %}
{%for topic in topics%}
<div class="row">
<a href="/topic/{{topic.id}}/"><h1>{{topic.name}}</h1></a>
<p>{{topic.blurb}}</p>
</div>
{% empty %}
There are currently no topics to browse
{% endfor %}
{% endautoescape %}
{%endblock%}